simaset/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/home2', function () {
    return view('home2');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/category','CategoryController');

Route::get('/', 'Auth\LoginController@index');
Route::post('/auth', 'Auth\LoginController@auth');
Route::get('auth/logout', 'Auth\LoginController@logout');

Route::group(['middleware' => ['authLogin']], function () {
    Route::get('/view/attachment/{url}', 'AttachmentController@index');
    Route::get('/md/kategori', 'Md\KategoriController@index');
    Route::get('/dashboard', 'Home\DashboardController@index');
    Route::group(['prefix' => 'md/asset'], function () {
        Route::get('/index', 'Md\AssetController@index');
        Route::get('/create', 'Md\AssetController@create');
        Route::post('/create', 'Md\AssetController@create');
        Route::get('/update/{id}', 'Md\AssetController@update');
        Route::post('/update/{id}', 'Md\AssetController@update');
        Route::post('/delete/{id}', 'Md\AssetController@delete');
    });
});

simaset/app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name','slug'];

    protected $table = 'category';
}

simaset/app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category = Category::paginate(10);
        return view('admin.category.index', compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' =>'required|min:3'
        ]);
        $category = Category::create([
            'name' => $request->name,
            'slug' => Str::slug($request->name)

        ]);

        return redirect()->back()->with('success','Kategori berhasil disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findorfail($id);
        return view('admin.category.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);
        
        $category_data = [
            'name' => $request->name,
            'slug' => Str::slug($request->name)
        ];

        Category::whereId($id)->update($category_data);

        return redirect()->route('category.index')->with('success','Data Berhasil di Update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findorfail($id);
        $category->delete();

        return redirect()->back()->with('success','Data Berhasil Dihapus');
    }
}

simaset/resources/views/admin/category/create.blade.php
@extends('template_backend.home')
@section('sub-judul','Tambahh Kategori')
@section('content')

    @if(count($errors)>0)
        @foreach($errors->all() as $error)
        <div class="alert alert-danger" role="alert">
        {{ $error }}
        </div>
           
        @endforeach
    @endif

    @if(Session::has('success'))
    <div class="alert alert-success" role="alert">
    {{ Session ('success')}}
        </div>
        
    @endif
    <form action="{{ route( 'category.store') }}" method="POST">
    @csrf
    <div class="form-group">
        <label>Kategori</label>
        <input type="text" class="form-control" name="name">
    </div>

    <div class="form-group">
        <button class="btn btn-primary btn-block">Simpan Kategory</button>
    </div>
    </form>


@endsection

simaset/resources/views/admin/category/edit.blade.php
@extends('template_backend.home')
@section('sub-judul','Edit Kategori')
@section('content')

    @if(count($errors)>0)
        @foreach($errors->all() as $error)
        <div class="alert alert-danger" role="alert">
        {{ $error }}
        </div>
           
        @endforeach
    @endif

    @if(Session::has('success'))
    <div class="alert alert-success" role="alert">
    {{ Session ('success')}}
        </div>
        
    @endif
    <form action="{{ route( 'category.update',$category->id )}}" method="POST">
    @csrf
    @method ('patch')
    <div class="form-group">
        <label>Kategori</label>
        <input type="text" class="form-control" name="name" value="{{ $category->name }}">
    </div>

    <div class="form-group">
        <button class="btn btn-primary btn-block">Update Kategory</button>
    </div>
    </form>


@endsection

simaset/resources/views/admin/category/index.blade.php
@extends('template_backend.home')
@section('sub-judul','Kategori')
@section('content')

    @if(Session::has('success'))
    <div class="alert alert-success" role="alert">
    {{ Session ('success')}}
        </div>
    @endif
    <a href ="{{ route('category.create') }}" class="btn btn-info btn-sm">Tambah Kategori</a>
    <br><br>

    <table class="table table-striped table-hover table-sm table-bordered">
        <thead>       
            <tr>
                <th>No</th>
                <th>Nama Kategori</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
         @foreach ($category as $result => $hasil)
            <tr>
                <td>{{ $result + $category->firstitem() }}</td>
                <td>{{ $hasil->name}}</td>
                <td>
                <form action="{{ route('category.destroy', $hasil->id)}}" method = "POST">
                @csrf
                @method('delete')
                <a href="{{route ('category.edit', $hasil->id)}}" class="btn btn-primary btn-sm">Edit</a>
                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    {{ $category->links() }}

@endsection